---
- name: Create kubeadm config
  template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml
- name: Master init
  shell: |
    kubeadm init --config=kubeadm-config.yaml --upload-certs
  register: output
  args:
    chdir: /tmp

- name: Set global variables
  set_fact:
    K8STOKEN: "{{ output.stdout | regex_search('(?<=token )[a-zA-Z0-9_]{6}.[a-z0-9_]{16}') }}"
    DISCOVERY_TOKEN_HASH: "{{ output.stdout | regex_search('(?<=sha256:)\\w+') }}"
    CERTIFICATE_KEY: "{{ output.stdout | regex_search('(?<=certificate-key )\\w+') }}"

