---
- name: Install haproxy
  yum:
    name: haproxy,keepalived
    state: latest

- name: Configure haproxy
  block:
    - template:
        src: "haproxy/{{ item }}"
        dest: "/etc/haproxy/{{ item.strip('.j2') }}"
      loop:
        - check_haproxy.sh.j2
        - haproxy.cfg.j2
    - name: start haproxy
      systemd:
        name: haproxy
        state: started
        enabled: yes

- name: Configure keepalived
  block:
    - template:
        src: haproxy/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
    - name: start keepalived
      systemd: 
        name: keepalived
        state: started
        enabled: yes

