- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Copy repo
  import_tasks: copy-k8sRepo.yaml

- name: Set open files limits 
  import_tasks: set-limits.yaml
  tags:
    - set-limits

- name: Set kernel parameters
  import_tasks: set-kernel-parameters.yaml
  tags:
    - set-kernel

- name: Pull images
  import_tasks: pull-Images.yaml
  delegate_to: 127.0.0.1
  run_once: True
  tags:
    - pull-images

- name: Load images
  import_tasks: load-images.yaml
  tags:
    - pull-images

- name: Install kubeadm and docker runtime
  import_tasks: install-kubeadmDocker.yaml
  tags:
    - install-kubeadm

- name: Install haproxy
  import_tasks: install-haproxy.yaml
  when: inventory_hostname in groups['master']
  tags:
    - install-haproxy

- name: Init cluster
  import_tasks: init-master.yaml
  run_once: True
  delegate_to: "{{ groups['master'][0] }}"
  tags:
    - init-master

- name: Join cluster
  import_tasks: join-cluster.yaml
  run_once: True
  delegate_to: "{{ groups['master'][1] }}"
  tags:
    - join-cluster

- name: Join cluster
  import_tasks: join-cluster.yaml
  run_once: True
  delegate_to: "{{ groups['master'][2] }}"
  tags:
    - join-cluster

- name: Install flannel cni
  import_tasks: install-flannel.yaml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: True
  tags:
    - install-flannel
